From centos
MAINTAINER comanche
COPY readme.txt /usr/local/readme.txt
ADD apache-tomcat-9.0.22.tar.gz /usr/local
ADD jdk-8u11-linux-x64.tar.gz /usr/local
RUN yum -y install vim
ENV MYPATH /usr/local
WORKDIR $MYPATH
ENV JAVA_HOME /usr/local/jdk1.8.0_11 #设置环境变量
ENV CATALINA_HOME /usr/local/apache-tomcat-9.0.22 #设置环境变量
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/lib # 设置环境变量 分隔符是：
EXPOSE 8080
CMD /usr/local/apache-tomcat-9.0.22/bin/startup.sh && tail -F /usr/local/apache-tomcat-9.0.22/logs/catalina.out #  设置默认命令
